name: Unit tests
      
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'
        
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.5', '2.6', '2.7', 'truffleruby' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle config build.nokogiri --use-system-libraries
        bundle install
        bundle exec appraisal install
        bundle exec appraisal rake test
